### PR TITLE
Fix #3167: avoid infinite wait on failure to init curl handle acquire

### LINKED ISSUE #3167: AWS::Http::CurlHandleContainer will cause the service to be permanently unavailable
### Describe the bug

The DestroyCurlHandle function will fail to rebuild the curl connection, but at this time m_poolSize has not changed, which may result in no connection available in the end. For example: there are N connections in the connection pool, and there are currently 2N concurrent requests. Unfortunately, the N threads that have obtained the connection have problems when making http calls, and DestroyCurlHandle fails to rebuild the curl connection. At this time, there is no connection in the connection pool, but m_poolSize is equal to m_maxPoolSize, so the blocked N threads cannot be awakened, and the new working thread will also be blocked, causing the service to be permanently unavailable.
2. If function AWS::Utils::ExclusiveOwnershipResourceManager::ShutdownAndWait  encounters the above situation, it will also be permanently blocked because it does not meet the condition of _resources.size() == resourceCount.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

none

### Current Behavior

I haven't actually encountered it, but it's a potential risk.

### Reproduction Steps

none

### Possible Solution

none

### Additional Information/Context

none

### AWS CPP SDK version used

1.11.438

### Compiler and Version used

 4.8.5 

### Operating System and version

linux

### PR DESCRIPTION
**Pull request by SergeyRyabinin**
*Issue #, if available:*
https://github.com/aws/aws-sdk-cpp/issues/3167
*Description of changes:*

*Check all that applies:*
- [ ] Did a review by yourself.
- [ ] Added proper tests to cover this PR. (If tests are not applicable, explain.)
- [ ] Checked if this PR is a breaking (APIs have been changed) change.
- [ ] Checked if this PR will _not_ introduce cross-platform inconsistent behavior.
- [ ] Checked if this PR would require a ReadMe/Wiki update.

Check which platforms you have built SDK on to verify the correctness of this PR.
- [ ] Linux
- [ ] Windows
- [ ] Android
- [ ] MacOS
- [ ] IOS
- [ ] Other Platforms

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: src/aws-cpp-sdk-core/include/aws/core/utils/ResourceManager.h [hunk 1]
```diff
@@ -74,6 +74,31 @@ namespace Aws
...
+             *
+             * @return instance of RESOURCE_TYPE, nullptr if the resource manager is being shutdown
+             */
+            template<typename std::enable_if<std::is_pointer<RESOURCE_TYPE>::value>::type * = nullptr>
+            RESOURCE_TYPE TryAcquire(const uint64_t timeoutMs) {
+              std::unique_lock<std::mutex> locker(m_queueLock);
+              const bool isNotEmpty = m_semaphore.wait_for(locker, std::chrono::milliseconds(timeoutMs),
+                                                           [&]() { return m_shutdown.load() || !m_resources.empty(); });
+
+              if (m_shutdown || !isNotEmpty) {
```
Comment (sbiscigl) [inline src/aws-cpp-sdk-core/include/aws/core/utils/ResourceManager.h:92]: nit `!` and `isNot` is kind of confusing could we just use `isEmpty` instead?

File: src/aws-cpp-sdk-core/source/http/curl/CurlHandleContainer.cpp [hunk 2]
```diff
@@ -44,7 +45,20 @@ CURL* CurlHandleContainer::AcquireCurlHandle()
         CheckAndGrowPool();
     }
 
-    CURL* handle = m_handleContainer.TryAcquire();
+    // TODO: 1.12: start to fail instead of infinite loop
+    CURL* handle = nullptr;
+    bool errorLogged = false;  // avoid log explosion on legacy app behavior
+    while (!handle && m_poolSize) {
+      constexpr unsigned long DEFAULT_TIMEOUT = 1000l;
+      handle = m_handleContainer.TryAcquire(std::max(m_connectTimeout, DEFAULT_TIMEOUT));
```
Comment (sbiscigl) [inline src/aws-cpp-sdk-core/source/http/curl/CurlHandleContainer.cpp:53]: i think we should use something else besides m_connectTimeout  as that maps one to one with `CURLOPT_CONNECTTIMEOUT_MS`, and we are sort of tying those together. this has its own unique meaning of "aquisition from the pool time", not "DNS lookup time". maybe create a static const/maybe add a config var if this would touch several clients.

**Review by sbiscigl — APPROVED** [review]

File: src/aws-cpp-sdk-core/include/aws/core/utils/ResourceManager.h (hunk 1 above)
Comment (sbera87) [reply src/aws-cpp-sdk-core/include/aws/core/utils/ResourceManager.h:92]: wait_for returns an enum. 
https://en.cppreference.com/w/cpp/thread/condition_variable/wait_for
Better to use this .
enum class cv_status {
    no_timeout,  => 0
    timeout    => 1
};

doesm't that mean return on !isNotEmpty is actually returning on no timeout. Is that the intention?

Comment (sbera87) [reply src/aws-cpp-sdk-core/include/aws/core/utils/ResourceManager.h:92]: Also, isNotEmpty can be renamed to isTimeOut for clarity

Comment (sbera87) [reply src/aws-cpp-sdk-core/include/aws/core/utils/ResourceManager.h:92]: Can we add a test case to test the timeout scenario, which should be easy to replicate

Comment (SergeyRyabinin) [reply src/aws-cpp-sdk-core/include/aws/core/utils/ResourceManager.h:92]: No it doesn't return an enum. Check the spec you linked for the (2) with predicate.

Comment (sbera87) [reply src/aws-cpp-sdk-core/include/aws/core/utils/ResourceManager.h:92]: that's right. looks ok then.  if you can add a test case that will be great

Comment (SergeyRyabinin) [reply src/aws-cpp-sdk-core/include/aws/core/utils/ResourceManager.h]: It is a really hard to test this piece of code: curl wrapper is hard-coded to a real c curl APIs, handle container is private and cannot be replaced.
I have a 1y old draft of curl wrapper refactoring: https://github.com/aws/aws-sdk-cpp/tree/sr/curlMulti2 which I still want to have merged one day. I can add curl wrapper unit tests there.

**Review by sbera87 — APPROVED** [review]

File: src/aws-cpp-sdk-core/include/aws/core/utils/ResourceManager.h (hunk 1 above)
Comment (sbera87) [reply src/aws-cpp-sdk-core/include/aws/core/utils/ResourceManager.h]: cool, thanks

Comment (SergeyRyabinin) [reply src/aws-cpp-sdk-core/include/aws/core/utils/ResourceManager.h]: Added a test on ResourceManager template class.

File: src/aws-cpp-sdk-core/source/http/curl/CurlHandleContainer.cpp (hunk 2 above)
Comment (SergeyRyabinin) [reply src/aws-cpp-sdk-core/source/http/curl/CurlHandleContainer.cpp]: Removed usage of m_connectTimeout, and just set 1s of wait time.

**Review by sbiscigl — APPROVED** [review]

**Review by sbera87 — APPROVED** [review]
